### PR TITLE
add docker compose file

### LINKED ISSUE #875: [FEATURE]  Add Docker Compose
### Is your feature request related to a problem? Please describe.
Now we use docker commands to run or build a container.  Would it be useful to use [Docker Compose](https://docs.docker.com/compose/) for managing them?

### Describe the solution you'd like
Compose simplifies the control of entire application stack, making it easy to manage services, networks, and volumes in a single, comprehensible YAML configuration file. Then, with a single command, you create and start all the services from a configuration file.

### Describe alternatives you've considered
N.A.
### Additional context
N.A.

### PR DESCRIPTION
**Pull request by benmalef**
Fixes #875

## Proposed Changes

-  Add compose.yaml file.  It is another way to manage and run commands in the docker.

You can check [ref](https://docs.docker.com/reference/cli/docker/compose/)

you can run 
```
docker compose up
```
to build and run your container

## Checklist

- [ ] [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide has been followed.
- [ ] PR is based on the [current GaNDLF master ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop?platform=windows).
- [ ] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [ ] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).
- [ ] Code has been [blacked](https://github.com/psf/black#usage) for style consistency and linting.
- [ ] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [ ] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) file.
- [ ] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate.
- [ ] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation.
- [ ] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/mlcommons/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/mlcommons/GaNDLF/blob/devcontainer_build_fix/Dockerfile-CUDA11.6),[3](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-ROCm)].
- [ ] The `logging` library is being used and no `print` statements are left.

### CODE REVIEW

**Comment by benmalef** [comment]
> Looks good, but should we not be using this for all Docker builds?

It's the same with [this](https://docs.mlcommons.org/GaNDLF/usage/#running-with-docker), IMO but in an easier way. 
You can modify the compose.yaml. You can choose the dockerfile, the volume, the commands that you want  to execute.

**Comment by sarthakpati** [comment]
> > Looks good, but should we not be using this for all Docker builds?
> 
> It's the same with [this](https://docs.mlcommons.org/GaNDLF/usage/#running-with-docker), IMO but in an easier way. You can modify the compose.yaml. You can choose the dockerfile, the volume, the commands that you want to execute.

Okay, then please provide clear examples of how this improves the existing docker workflow.

**Comment by benmalef** [comment]
I have created an example to demonstrate how to use it, but I have noticed that extra effort is required from the user to modify the compose.yaml file. 

Using the docker command line
```
docker run -it --rm --name dataprep \
  --volume /home/researcher/gandlf_input:/input:ro \ # input data is mounted as read-only
  --volume /home/researcher/gandlf_output:/output \ # output data is mounted as read-write
  cbica/gandlf:latest-cpu \ # change to appropriate docker image tag
  construct-csv \ # standard construct CSV API starts
  --input-dir /input/data \
  --output-file /output/data.csv \
  --channels-id _t1.nii.gz \
  --label-id _seg.nii.gz
```
Using the docker compose file. 

```
version: '1'

services:
  gandlf:
    build:
      context: .
      dockerfile: Dockerfile-CPU #choose the dockerfile
#    volumes: 
#     - /home/researcher/gandlf_input:/input:to
       - /home/researcher/gandlf_output:/output
    entrypoint: ["gandlf"]
    command: ["construct-csv",
"--input-dir ","/input/data",
"--output-file ","/output/data.csv",
" --channels-id"," _t1.nii.gz ",
" --label-id", "_seg.nii.gz" ] 
```
You can run  `docker compose up ` to run the container and execute the command.

**Comment by sarthakpati** [comment]
@hasan7n since you are far more familiar with docker than I am, what are you views on this?

**Pull request closed without merging**
