### PR TITLE
Add a new optimizer

### LINKED ISSUE #869: [FEATURE] add the nadam optimizer
### Is your feature request related to a problem? Please describe.
The nadam optimizer incorporates nestrov momentum into the Adam optimizer, thus providing potentially better solutions: https://openreview.net/forum?id=OM0jvwB8jIp57ZJjtNEZ 

### Describe the solution you'd like
PyTorch has this [[ref](https://pytorch.org/docs/stable/generated/torch.optim.NAdam.html)], and it would be good to expose the api through the configuration definition. 

### Describe alternatives you've considered
N. A. 

### Additional context
N. A.

### PR DESCRIPTION
**Pull request by pranayasinghcsmpl**
Fixes #869 

## Proposed Changes

- import nadam from torch.optim in wrap_torch.py
- create nadam function to handle parameters in wrap_torch.py
- update nadam optimizer in __init__.py

## Checklist

- [ ] [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide has been followed.
- [ ] PR is based on the [current GaNDLF master ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop?platform=windows).
- [ ] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [ ] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).
- [ ] Code has been [blacked](https://github.com/psf/black#usage) for style consistency and linting.
- [ ] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [ ] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) file.
- [ ] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate.
- [ ] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation.
- [ ] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/mlcommons/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/mlcommons/GaNDLF/blob/devcontainer_build_fix/Dockerfile-CUDA11.6),[3](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-ROCm)].

### CODE REVIEW

**Comment by pranayasinghcsmpl** [comment]
@sarthakpati While linting (using black .) i am getting the following error:

error: cannot format D:\Workspace\gandlf\fork\GaNDLF\testing\entrypoints\__init__.py: Cannot parse: 321:26:                         ) as e,
Oh no! 💥 💔 💥
170 files left unchanged, 1 file failed to reformat

**Comment by sarthakpati** [comment]
> @sarthakpati While linting (using black .) i am getting the following error:
> 
> error: cannot format D:\Workspace\gandlf\fork\GaNDLF\testing\entrypoints__init__.py: Cannot parse: 321:26: ) as e, Oh no! 💥 💔 💥 170 files left unchanged, 1 file failed to reformat

@VukW or @szmazurek could you perhaps check this?

**Comment by szmazurek** [comment]
Hey there! I took a look and actually, I failed to replicate the error you are seeing @pranayasinghcsmpl, are you sure there were no syntax errors in your local code when you were running it? Also maybe try to call `black -v .` flag to see the output verbose. The rest of the failed black tests were due to unformatted files present, I have done the formatting and pushed changes, and now the black test is passing. Probably due to this failure the black did not format those other files and that's why the CI failed.

**Comment by pranayasinghcsmpl** [comment]
Thanks @szmazurek

**Review by szmazurek — APPROVED** [review]
LGTM

**Pull request merged**
