### PR TITLE
Add Torch profiling

### LINKED ISSUE #639: Better code profiling
**Is your feature request related to a problem? Please describe.**
Currently, all the code profiling is custom based on internal functions from psutil and/or pytorch. It would be great to have a more uniform solution.

**Describe the solution you'd like**
I found a few options:
- [Torch Profiler](https://pytorch.org/docs/1.13/profiler.html?highlight=profiler#module-torch.profiler): Pros: extensive pytorch-specific debugging information; cons: requires changes to the training/inference apis of GaNDLF
- [Scalene](https://github.com/plasma-umass/scalene): Pros: straightforward `start` and `stop` for pieces of code that are to be profiled; cons: generic hardware-level information
- [octoml](https://github.com/octoml/octoml-profile): Pros: potential acceleration of prediction; cons: requires modification of model code, PyTorch-2.0 needed
- [DLProf](https://docs.nvidia.com/deeplearning/frameworks/dlprof-user-guide/#py_torch): Pros: CLI-based; cons: doesn't seem to give pytorch-specific information
- [HolisticTraceAnalysis](https://github.com/facebookresearch/HolisticTraceAnalysis): Pros: tight integration with PyTorch; cons: very new library so might need to see how this develops

We should have a detailed discussion on any potential requirements and how we can evaluate these libraries.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

### PR DESCRIPTION
**Pull request by pranayasinghcsmpl**
Fixes #639 

## Proposed Changes

- Added Profiling option in `run` command
- Added Torch Profiler that prints `cpu_time_total` for both CPU & GPU

## Checklist

- [ ] [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide has been followed.
- [ ] PR is based on the [current GaNDLF master ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop?platform=windows).
- [x] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [ ] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).
- [x] Code has been [blacked](https://github.com/psf/black#usage) for style consistency and linting.
- [ ] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [ ] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) file.
- [ ] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate.
- [ ] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation.
- [ ] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/mlcommons/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/mlcommons/GaNDLF/blob/devcontainer_build_fix/Dockerfile-CUDA11.6),[3](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-ROCm)].

### CODE REVIEW

**Comment by sarthakpati** [comment]
Please update the tests (or add a new one) to ensure that the new code is covered, and we are going to wait till #845 is merged to merge this in.

**Comment by pranayasinghcsmpl** [comment]
Alright, no problem.

**Comment by sarthakpati** [comment]
Please change the base of this PR to master.

**Comment by pranayasinghcsmpl** [comment]
Sure, I am working on a way to avoid the test case errors.

**Comment by sarthakpati** [comment]
@pranayasinghcsmpl - wanted to touch base about this.

**Pull request closed without merging**
