### PR TITLE
Updated devcontainer requirements for PyTorch and CUDA

### LINKED ISSUE #598: Updated devcontainer requirement to Torch 1.13 and CUDA 11.6
**Is your feature request related to a problem? Please describe.**
Currently, the devcontainer is based on the older torch and cuda versions, which GaNDLF has moved on from (#590).

**Describe the solution you'd like**
The devcontainer definitions need to be updated.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixes #598 

## Proposed Changes

- updated requirements for torch and cuda
- no need to calculate code coverage for this folder
- added CI to test devcontainer on every PR, and to build a new one on every upstream merge

## Checklist

- [x] I have read the [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide
- [x] My PR is based from the [current GaNDLF master ](https://garygregory.wordpress.com/2016/11/10/how-to-catch-up-my-git-fork-to-master/)
- [x] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change 
- [x] Function/class source code documentation added/updated
- [x] Code has been [blacked](https://github.com/psf/black#usage) for style consistency
- [x] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py)
- [x] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) file 
- [x] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate
- [x] [History](https://github.com/mlcommons/GaNDLF/blob/master/HISTORY.md) has been updated, if appropriate
- [x] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation
- [x] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/mlcommons/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CUDA10.2),[3](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CUDA11.3),[4](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-ROCm)]

### CODE REVIEW

**Comment by samruddhikhandale** [comment]
> Is there a way for us to automate the testing of the devcontainer creation (perhaps along with the gandlf_verifyInstall script to ensure that the environment is correctly set up)?

You can create a dev container with @devcontainers/cli and add checks to the dev container.
Eg. Reference - This is how a container is built with [build.sh](https://github.com/devcontainers/images/blob/main/.github/actions/smoke-test/build.sh) and tested with [test.sh](https://github.com/devcontainers/images/blob/main/.github/actions/smoke-test/test.sh )

@sarthakpati Probably you could do something similar to validate the dev config?

> Can we add some relevant documentation for users to get started with this in an easy way?

I am not sure if I understand your question, are you looking forward to update your contribution docs with "Getting Started with Codespaces" section? I can help add that if needed.

**Comment by samruddhikhandale** [comment]
> EDIT: Would [this action](https://github.com/marketplace/actions/devcontainers-ci) be something that can be used for this purpose?

Yep, I think so. You might be interested in "Using a Dev Container for a CI build:" section of https://github.com/devcontainers/ci/blob/main/docs/github-action.md

**Comment by samruddhikhandale** [comment]
Opened https://github.com/mlcommons/GaNDLF/pull/602 ⚡

**Comment by gwincr11** [comment]
We offer prebuilds as a feature, you can pin it to a branch like main: https://docs.github.com/en/codespaces/prebuilding-your-codespaces

You can open a container as a gpu instance from this page, that lets you choose options for the machine type 
https://github.com/codespaces/new?hide_repo_select=true&ref=master&repo=342691278

You get there from the code drop down, then clicking on the `...` on the right side of the new codespace option.

This should give you Cuda bindings I believe as that is a devcontainer feature.

**Review by Geeks-Sid — APPROVED** [review]

**Pull request merged**
