### PR TITLE
Sort imports following PEP-8 to improve readability

### PR DESCRIPTION
**Pull request by Geeks-Sid**
This improves the readability of imports and follows the PEP-8 [import](https://peps.python.org/pep-0008/#imports) guidelines

## Proposed Changes

Sorted all imports in gandlf

## Checklist

- [x] I have read the [`CONTRIBUTING`](https://github.com/CBICA/GaNDLF/blob/master/CONTRIBUTING.md) guide
- [x] My PR is based from the [current GaNDLF master ](https://garygregory.wordpress.com/2016/11/10/how-to-catch-up-my-git-fork-to-master/)
- [x] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change 
- [x] Function/class source code documentation added/updated
- [x] Code has been [blacked](https://github.com/psf/black#usage) for style consistency
- [x] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/CBICA/GaNDLF/blob/master/GANDLF/version.py)
- [x] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/CBICA/GaNDLF/blob/master/pyproject.toml) file 
- [ ] [Usage documentation](https://github.com/CBICA/GaNDLF/blob/master/docs) has been updated, if appropriate
- [ ] [History](https://github.com/CBICA/GaNDLF/blob/master/HISTORY.md) has been updated, if appropriate
- [x] Tests added or modified to [cover the changes](https://app.codecov.io/gh/CBICA/GaNDLF); if coverage is reduced, please give explanation
- [x] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/CBICA/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/CBICA/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/CBICA/GaNDLF/blob/master/Dockerfile-CUDA10.2),[3](https://github.com/CBICA/GaNDLF/blob/master/Dockerfile-CUDA11.3),[4](https://github.com/CBICA/GaNDLF/blob/master/Dockerfile-ROCm)]

### CODE REVIEW

**Comment by Geeks-Sid** [comment]
Does it make sense to add it in currently in the latest release to look good at least?

**Comment by AlexanderGetka-cbica** [comment]
@Geeks-Sid Can you send me all the parameters used for isort, if any were non-default? I'm looking into doing this from Black.

**Comment by Geeks-Sid** [comment]
> @Geeks-Sid Can you send me all the parameters used for isort, if any were non-default? I'm looking into doing this from Black.

Just used the defaults for solving imports.

**Comment by AlexanderGetka-cbica** [comment]
OK, so this isn't actually possible to do directly from black [[ref](https://github.com/psf/black/issues/333)], in part because import order can actually have functional effects on the code. If we insist on isort ordering, we will need to run isort separately. 

I can (trivially) implement the check for whether isort's requirements are met. We should be able to achieve compatibility between the two checks by setting isort's config to black. I'll check to see if this produces different output and post back.

There is another thing to bring up: 
How do we feel about [pre-commit](https://pre-commit.com/) for things like this? This would run the black and isort steps before each commit, and we could add other tools to it down the line easily. The downsides is that in very esoteric corner cases, the author might commit and not see that black/isort has made some kind of breaking change. And also that people contributing to GaNDLF would need to install it unless they decide to run black/isort manually.

**Pull request closed without merging**
