### PR TITLE
Convert main scripts to console entry points

### LINKED ISSUE #610: Convert main scripts to console entry points
**Is your feature request related to a problem? Please describe.**
Currently, GaNDLF's main interactive components are based on standalone scripts, which are an older way of defining python packages.

**Describe the solution you'd like**
Converting them to dedicated functions with console entry points would be better (a good read on why is [here](https://stackoverflow.com/questions/18787036/difference-between-entry-points-console-scripts-and-scripts-in-setup-py)), and more compatible with future changes in python.

**Describe alternatives you've considered**
N.A.

**Additional context**
More details in: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

### PR DESCRIPTION
**Pull request by sunny1401**
Fixes #610 

## Proposed Changes
- Moved all interactive to within cli as in the comments here
- Updated the setup file
- Removed the prior scripts
- Updated to major version change to avoid breaking anything

## Checklist

- [x] I have read the [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide.
- [x] My PR is based from the [current GaNDLF master ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop?platform=windows).
- [x] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [x] Function/class source code documentation added/updated.
- [x] Code has been [blacked](https://github.com/psf/black#usage) for style consistency.
- [x] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [ ] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate.
- [x] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation.

### CODE REVIEW

**Comment by sunny1401** [comment]
@sarthakpati  - Hi, I have an initial PR - I need to update docs etc - but could you have a look and see if this is on the right track please

**Comment by sunny1401** [comment]
@sarthakpati - Hi sorry this is going slow.. I wanted to ask one additional thing. How does the versioning work - most of the test fail cause of 

```python
{'maximum': '0.0.17', 'minimum': '0.0.14'}

````

However, because this change is changing the way functionality is being accessed - I added it as a major version change instead of minor version change. The above tests only allow bug version updates; but I don't think this is a bug. Could you clarify?

**Comment by sunny1401** [comment]
Hi sorry- I added some test cases but I haven’t finished and I am not
actively on it anymore.

**Comment by VukW** [comment]
No way, machine, it's still active

**Comment by sarthakpati** [comment]
This has been superseded by #818

**Pull request closed without merging**
