### PR TITLE
Adding function to get augmentation transforms

### LINKED ISSUE #888: [FEATURE] add function to retrieve augmentations from config
### Is your feature request related to a problem? Please describe.
N/A

### Describe the solution you'd like
Add a function that would handle getting augmentation transforms from parameters. Would also be useful in future gandalf-dependent packages.

### Describe alternatives you've considered
N/A

### PR DESCRIPTION
**Pull request by szmazurek**
Fixes #888

## Proposed Changes
-  function for getting the augmentation transforms from params dict
- using that function in dataset constructor

## Checklist

- [X] [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide has been followed.
- [X] PR is based on the [current GaNDLF master ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop?platform=windows).
- [X] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [X] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).
- [X] Code has been [blacked](https://github.com/psf/black#usage) for style consistency and linting.
- [X] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [ ] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) file.
- [X] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate.
- [ ] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation.
- [ ] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/mlcommons/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/mlcommons/GaNDLF/blob/devcontainer_build_fix/Dockerfile-CUDA11.6),[3](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-ROCm)].

### CODE REVIEW

**Comment by sarthakpati** [comment]
Please change the base to https://github.com/mlcommons/GaNDLF/tree/new-apis_v0.1.0-dev

**Comment by szmazurek** [comment]
> Member

Done, not sure if we should re-run the tests somehow

**Comment by VukW** [comment]
Hi! Folks, by some strange reason this PR didn't trigger CI tests at all. However, it brought a bug (failing test) inside base branch, that failed in a neighbor PR: https://github.com/mlcommons/GaNDLF/actions/runs/9724955407/job/26841721449?pr=890 I'm not sure if it's the only failure. @szmazurek can you plz run the tests locally to check if everything behaves as you expected in the PR?

**Comment by szmazurek** [comment]
@VukW on it!

**Comment by sarthakpati** [comment]
@szmazurek are you looking into the error? Starting to see this pop up for other PRs as well.

**Comment by VukW** [comment]
Checking fix here: https://github.com/mlcommons/GaNDLF/pull/890/commits/c312e24ce99540f081c38e72922113cb73b06c57
https://github.com/mlcommons/GaNDLF/pull/890

**Comment by sarthakpati** [comment]
> Checking fix here: [c312e24](https://github.com/mlcommons/GaNDLF/commit/c312e24ce99540f081c38e72922113cb73b06c57) #890

Thanks, @VukW! 

I am guessing that fixed it, because at least one of the tests that was breaking before is now functional.

**Comment by VukW** [comment]
+, all tests are running successfully now. Merged the fix together with #890 .

**Comment by szmazurek** [comment]
Hey guys, I had a chance to look at that closely just now, but I see @VukW already fixed that - thanks!

**Pull request merged**
