### PR TITLE
Fix deployment to work when installed from wheel

### PR DESCRIPTION
**Pull request by AlexanderGetka-cbica**
Attempts to fix one aspect of #629.

WARNING: The changes needed to make this work without restructuring the entire repo are pretty wacky, bear with me when reading the below.

Deployment was failing from GaNDLF installed via wheel/from pip largely because the directory structure in this case is NOT equivalent to the source repo's structure (i.e., from `pip install -e .` in the git repo). 
Trying to install the dockerfiles/other files needed for setup into the installed package is difficult for various reasons related to implementation details in setuptools, etc.
In order to avoid restructuring the entire repository, I decided to leave these files in the top-level site-packages directory, and "install them" during deployment. 
This means turning the GaNDLF package directory into something that, itself, can be installed.
So we use some tricks that require us to exclude the other stuff inside the package from being installed, including making a recursive symlink to the GaNDLF package so that the code gets bundled, but change setup.py to exclude the package from being installed by itself. (Isn't recursion fun?)

## Proposed Changes

- deploy script now checks for the case where GaNDLF is installed directly as a package in site-packages
- We now bundle the extra setup-related files and install to site-packages
- deploy script now uses these to generate the install inside the container

## Checklist

- [x] I have read the [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide.
- [x] My PR is based from the [current GaNDLF master ](https://garygregory.wordpress.com/2016/11/10/how-to-catch-up-my-git-fork-to-master/).
- [x] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [x] Function/class source code documentation added/updated.
- [x] Code has been [blacked](https://github.com/psf/black#usage) for style consistency.
- [x] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [x] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) file.
- [x] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate.
- [x] [History](https://github.com/mlcommons/GaNDLF/blob/master/HISTORY.md) has been updated, if appropriate.
- [x] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation.
- [x] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/mlcommons/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/mlcommons/GaNDLF/blob/devcontainer_build_fix/Dockerfile-CUDA11.6),[3](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-ROCm)].

### CODE REVIEW

**Comment by hasan7n** [comment]
@AlexanderGetka-cbica how are you testing this?

I `pip install`ed gandlf from source and tested that deployment works fine. But do you know how I can "simulate" having it installed just like `pip install gandlf` from pypi?

I did `pip install . -t <some_folder>` and visually inspected that folder. I can see that it is installed according to your description above. So this looks good, but any idea if there is a better way for testing?

**Comment by AlexanderGetka-cbica** [comment]
In my case, I am just generating a wheel, and installing from that. the Python "build" tool can do this, e.g. from the source repo:

pip install build
python -m build

(you might be able to get it to build just the wheel and not also the source distribution). This is also how we create the nightly builds. 

Then install the wheel directly
pip install GaNDLF_[...]_py38.whl

**Comment by AlexanderGetka-cbica** [comment]
I am not sure how testing could cover this. We could make the testing pipeline cover the entire build->upload->install->run tests, but i don't know if pytest even supports this use.

**Review by hasan7n — DISMISSED** [review]
Thanks @AlexanderGetka-cbica ! It works

**Pull request merged**
