### PR TITLE
Updated CLI options for new API

### LINKED ISSUE #849: [FEATURE] Standardize the CLI option for output directory
### Is your feature request related to a problem? Please describe.
Currently, there are multiple types of "output" used in CLI, which can get confusing.

### Describe the solution you'd like
For anything related to output directory, it should be `outputdir` or something similar.

### Describe alternatives you've considered
N.A.

### Additional context
Update documentation as well.

### PR DESCRIPTION
**Pull request by scap3yvt**
Fixes #849, #851

## Proposed Changes

- updated cli options for the new cli

## Checklist

- [x] [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide has been followed.
- [x] PR is based on the [current GaNDLF master ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop?platform=windows).
- [x] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [x] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).
- [x] Code has been [blacked](https://github.com/psf/black#usage) for style consistency and linting.
- [x] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [x] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) file.
- [x] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate.
- [x] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation.
- [x] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/mlcommons/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/mlcommons/GaNDLF/blob/devcontainer_build_fix/Dockerfile-CUDA11.6),[3](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-ROCm)].

### CODE REVIEW

**Review by VukW — CHANGES_REQUESTED** [review]
Hi man, thank you for the improvement!
Can you plz to fix the failing tests:

1. to fix `CI-PyTest` you need to reflect your changes in tests also: `testing/entrypoints/test_XXXXX.py`.
2. To fix `MLCube-Test` you need to merge the base branch `new-apis_v0.1.0-dev` to your branch, I already fixed failures there

**Comment by scap3yvt** [comment]
I think this should be ready, @VukW!

**Comment by VukW** [comment]
Hi @scap3yvt ! I don't know why CI didn't trigger pytest after last merge, but for me locally tests fail, in particular these two:
https://github.com/mlcommons/GaNDLF/blob/new-apis_v0.1.0-dev__849-standardize_cli_options/testing/entrypoints/test_preprocess.py
https://github.com/mlcommons/GaNDLF/blob/new-apis_v0.1.0-dev__849-standardize_cli_options/testing/entrypoints/test_patch_miner.py

that's reasonable as they use old param names. Also, tests on old way scripts fail also, say [here](https://github.com/mlcommons/GaNDLF/pull/853/files#diff-11590e229960ea2894a36f80686b753eab608b595f9267d44c9e298e4d9c6812L187) (and same fore patch_miner)

You can check tests locally via `pytest ./testing/entrypoints/test_preprocess.py`  and `pytest ./testing/entrypoints/test_patch_miner.py`

**Comment by sarthakpati** [comment]
I am curious why the tests are not getting triggered...

**Comment by VukW** [comment]
@sarthakpati I checked the workflow, it's triggered only on PR to master:
```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```
(as well as codacy, codeql-analysis, devcontainer, mlcube-test, openfl-test, ossar-analysis workflows)

**Comment by sarthakpati** [comment]
Ah thanks! I am going to put a PR about that now.

**Review by VukW — APPROVED** [review]
LGTM

**Pull request merged**
